### ISSUE TITLE
inconsistent navigation to and from Curated Topics Index page and Sample

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#107]
From the Pages home, a folder labelled "Black Metropolis Research Consortium" is displayed. Clicking the arrow takes me to a list of available pages to edit. I see the following:
- Portal
- newTestPage (I need to delete this)
- Test (not mine)
- Contact Us
- About the BMRC
- Collections on Black Experiences
- Resources
- Programs
- News
Click on big arrow to the right of the Portal label; a list of Portal sub-pages appears (reason for capitalization differences?):
- Curated Topics
- about
- help
- Exhibits
If I click on the label "Curated Topics" it's to edit the CT Index page. IF I click the big arrow at the right I do get to the Sample child page. However, the link at the top is labeled "Curated Topics" but it always takes me to the Sample page, not to the index page as I would expect.

**Comment by johnjung** [comment]
This is expected behavior in Wagtail. 

Regarding capitalization: the Wagtail admin sidebar uses the same capitalization as the Title of each page. If you'd like you can edit the "about" page and the "help" page to capitalize each title, and then you'll see those changes reflected in the admin sidebar. 

I'm not able to duplicate the problem you describe at the bottom. From the Wagtail admin sidebar, if I click "Portal", one of the pages I see is "Curated Topics"- the Curated Topic Index Page. Clicking the right arrow shows me the "Curated Topic Sample", and above that is a link to "Curated Topics". That link leads back to the Curated Topic Index page. If I click that link above I do go back to the Curated Topic Index page, like I would expect.

**Comment by MomoMoses** [comment]
Here's where I go when I click the Curated Topics (Index) at the tip top of the page. Is this correct?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3534298/150441964-a5e0309c-869e-4cca-af88-72330c0f0b9b.png">

**Comment by johnjung** [comment]
Yes, this looks correct to me.

**Comment by johnjung** [comment]
Please close out this issue if it's appropriate to, otherwise please provide additional information so I can keep debugging.
