### ISSUE TITLE
some YouTube video will not embed even after Wagtail upgrade

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#112]
using the video command in the Rich Text box, the video appears in the box in the admin interface but does not appear in the preview.
here is the video I am trying to embed, in case it's something about the video (which would be good to know in any case) or if it's another issue entirely.
[here's the pesky video](https://youtu.be/bql7-mhz9Cc)

**Comment by johnjung** [comment]
I'm not able to duplicate the problem. [Here is a page where I used the embed tool in the Rich Text editor to add a video.](https://bmrc-test.lib.uchicago.edu/portal/about/) Could you provide more detail about the steps you're taking to try to add the video?

**Comment by MomoMoses** [comment]
Rats, I did not include the page title or link in this issue. I can't find the video I tried to embed and failed with. I will close this and re-open if necessary.

**Comment by MomoMoses** [comment]
Ok same video. I tried it in the top narrative paragraph on the Portal home page 
[portal home page](https://bmrc-test.lib.uchicago.edu/portal/)
take a look at the draft page which shows the video; the preview or live version does not.

**Comment by johnjung** [comment]
It looks like videos don't embed correctly when they're in plain RichText fields. The introductory content at the top of the PortalIndexPage is a "plain" RichText field, as are many of the fields on the CuratedTopic page. I checked that page too and found that videos don't embed correctly there either. 

Videos do embed correct in RichText fields that are part of StreamFields, however. ExhibitPages and PortalStandardPages are two examples of pages that use RichText fields in StreamFields specifically. 

This bug is probably going to be a bit more subtle than some of the others on the list, and it might take some time to dig into. Please let me know if it's possible, for the time being, for you to only embed videos in pages that use StreamFields.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/f5c43282859bf37e1a0c3a125c367cd26bdd1219.
