### ISSUE TITLE
Member highlight archives query is not documented

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#124]
Right now, it seems to appear magically! :)

It's not editable, which is fine, as all of the highlights will end exactly in the same way, by constructing a query of the database using the name of the archives being highlighted.

I like how the site's management and how data populates page areas is self-documenting in the Wagtail admin UI itself. This way external documents don't need to be maintained and pointed to going forward as responsibility for updating and managing the site shifts over time to new personnel. It would be beneficial to make sure that this method is complete for the whole site if at all possible. I think it may be 98% there already!

**Comment by MomoMoses** [comment]
here is the current blurb explaining how the member highlight works:
The member highlight section of the PortalHomePage cycles through Archive objects that have is_member attributes set to true. The member highlight will be updated on the first day of each month. The rotation order is determined by the order attribute of each Archive object. You can edit the content that appears for each Archive and the order they appear in by selecting the Archives link in the Wagtail admin sidebar.

**Comment by MomoMoses** [comment]
useful to add a line explaining that the query is auto-created using the name of the archives and giving an example of the query URL.

**Comment by johnjung** [comment]
This continues [a previous issue](https://github.com/johnjung/bmrcportal/issues/111).

Here, the query doesn't actually use the name of the archives. After sorting archive objects based on the order attribute, objects should be sorted in database order- in other words, if two archive objects have exactly the same value for order, the archive object that was added to the system first should display first.

Also, there is no URL for the query. If someone has shell access to the server they could use [this line](https://github.com/uchicago-library/bmrc/blob/40e586b8f2ecef51db992592fdf487757bd6065a/portal/models.py#L90) to debug the order.  We do that when we're debugging the system, however, that isn't something we normally document for end users. 

Please let me know if something is still missing from the documentation. If you have an exact change I can make to the current blurb please let me know- otherwise I think that the current explanation does explain how the system works well enough that someone using the admin panel can understand it. Basically, to change the order that member highlights appear in, you have to change the order attribute.

**Comment by MomoMoses** [comment]
This issue is not about the order of the highlights' appearance, rather how the query is formulated.
I do think that the explanation and how to change it using the order attribute is clear and complete.

For an example on this issue, here is the query for the current Member Highlight, Shorefront:
[Automagical query](https://bmrc.lib.uchicago.edu/portal/search/?f=https%3A//bmrc.lib.uchicago.edu/archives/Shorefront%2BLegacy%2BCenter)
https://bmrc.lib.uchicago.edu/portal/search/?f=https%3A//bmrc.lib.uchicago.edu/archives/Shorefront%2BLegacy%2BCenter

Usually I see "q" in a query. I don't know why there is an "f" instead, nor why that whole link is displayed in that manner. That query was formulated behind the scenes, and there is nothing visible or documented in the admin interface for the link. It's the standard link used at the bottom of every Highlight directing folks to "View collections..." at that repository.

**Comment by johnjung** [comment]
In this case, the entire URL is a search- when Wagtail sees a URL beginning with "https://bmrc.lib.uchicago.edu/portal/search/", it passes that URL to a search function for further processing.

When the search function gets a "q" parameter it does a full text search for that search term. In addition to that, or instead of that, when the search function gets one or more "f" parameters, it restricts the set of search result to documents that are included in those specific MarkLogic collections. 

MarkLogic collections are represented by URIs that are not dereferenceable- in other words, the user will probably not be able to cut and paste the URI after the "f" parameter to be able to go to a web page. Instead, in this context, we just use URIs because they're globally unique and we know that there won't be any collisions between different facets.

A lot of systems don't include this level of detail about the way URLs are constructed. Is it still helpful to include some of this detail? If so, could you write a draft of what the text in the Wagtail admin should be?

**Comment by MomoMoses** [comment]
👍 
Personally I LOVE that level of detail! But no, we don't need to include it for future database maintainers.
How about adding a sentence to the existing explanation on the BMRC Portal home page? Here's the initial blurb there:
"The member highlight section of the PortalHomePage cycles through Archive objects that have is_member attributes set to true. The member highlight will be updated on the first day of each month. The rotation order is determined by the order attribute of each Archive object. You can edit the content that appears for each Archive and the order they appear in by selecting the Archives link in the Wagtail admin sidebar."
### Add this:
"Shown under the Highlight is a standard, non-editable link to View Collections at that institution. It is formed behind the scenes as a search function."

**Comment by johnjung** [comment]
Ok, this is now implemented in https://github.com/uchicago-library/bmrc/commit/87ad702295791d467fe493aa200e8cadfb26fd70 and live on bmrc-test.lib. Please take a look and let me know if this is ok.

**Comment by MomoMoses** [comment]
Looks fine on the test site.
