### ISSUE TITLE
portal home page footer not editable

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#129]
what is the rationale? it shouldn't change a lot, so generally that's fine, but I can foresee a case where we might want to add a link or change something in that footer in years to come.

**Comment by johnjung** [comment]
This is because we have a limited amount of dev time to commit to your project. We often don't get around to implementing features like this one because dev time is better spent on features you'll use more often or get more benefit from.

If you'd like to update the footer in the future you can just put in a request to the DLDC. Alternatively, if an editable footer is important to you, you can request it as a new feature and David can schedule that.

**Comment by MomoMoses** [comment]
makes sense. of course a footer is not going to rise to the top of the list unless a specific case comes up! at that time we can request it from DLDC.
