### ISSUE TITLE
Top brief summary of the collection info should have a consistent heading

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#135]
In the UIC.AFSC collection, the heading is RECORDS SUMMARY whereas the intended heading should be DESCRIPTIVE SUMMARY across the board.

I see that there is a supplied heading in this case -- I still think it's confusing to use that heading vs. the one that's used throughout the system for almost everything else.

**Comment by johnjung** [comment]
In general I think the best policy is to prioritize the headings in the finding aid itself, because it's confusing when something that is explicitly included in XML is overwritten by a transformation. If you can, I think it's best to edit the finding aid itself in this case. 

However, if you'd still rather fix this in the XSLT just let me know.

**Comment by MomoMoses** [comment]
overidden, not changing the data. :)
all descriptive summary sections should have "DESCRIPTIVE SUMMARY" as the heading regardless of code

**Comment by johnjung** [comment]
This is now updated in https://github.com/uchicago-library/bmrc/commit/22e59606b4dbd712dbcfe9328be748e264c699e7 and live on the server. Please take a look and let me know if there is anything else I can change.

**Comment by MomoMoses** [comment]
Looks good!
