### ISSUE TITLE
Sorting order for Titles: depends on how they are entered

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#139]
It could be useful to add an element to the encoded finding aids for a "filing" (sort) title. This is provided for in EAD, but is not uniformly used.

End result is that A-Z sorts and listings are in many cases by first name or simply the beginning characters of the title data value and not according to guidelines for alphabetizing lists of materials.

**Comment by MomoMoses** [comment]
How broadly is the @type="filing" attribute used, and is this of value for sorting the SERPs displays? See issue #134 for more context on title elements. Need a report on ubiquity of @type attribute usage. Also evaluate how complex a change this would be for sorting results. It would NOT be used for any kind of display.

**Comment by johnjung** [comment]
As per Charles on 3/18 this can be implemented in this round of work.

**Comment by MomoMoses** [comment]
Sweet! 
PS I'd be interested in seeing the report on how much the @type="filing" attribute occurs in the data.
To reiterate, it would be used solely to determine sort order of listings.

**Comment by johnjung** [comment]
In 71 cases, there is a filing title at:
/ead:ead[1]/ead:eadheader[1]/ead:filedesc[1]/ead:titlestmt[1]/ead:titleproper[@type="filing"]

There is also one lone `unittitle type="filing"` in the system. Please note that the titleproper above is NOT the one that we're currently using in the h1 on the finding aid view or on the SERP or browse pages- that titleproper is at ead:ead[1]/ead:frontmatter[1]/ead:titlepage[1]/ead:titleproper[1]. (I.e., we're using the titleproper in the frontmatter, not in the eadheader.)

Here are some of the titleproper elements we're using for titles, along with the corresponding filing title, when it's present:

BMRC.NU.CITIZENS_FOR65.xml
 Title: Guide to the Records of the Citizens for 65 1953/2003
Filing: Citizens for 65, Records of the

BMRC.NU.UNIV_THEATRE_PHOTO.xml
 Title: Guide to the University Theatre Production Photographs 1928/1991
Filing: University Theatre Production Photographs

BMRC.NU.TURNER_L.xml
 Title: Guide to the Lorenzo Dow Turner Papers 1915/1973
Filing: Turner, Lorenzo Dow Papers

BMRC.NU.AFRSTUDIES.xml
 Title: Guide to the Program of African Studies Records 1955/1991
Filing: Program of African Studies Recordsinu-ead-nua-archon-1372

BMRC.NU.SETTLEMENT_DELINQ.xml
 Title: Guide to the Northwestern University Settlement Association Delinquent Boy Case Files 1929/1939
Filing: Northwestern University Settlement Association Delinquent Boy Case Files

BMRC.NU.SETTLEMENT_CASE.xml
 Title: Guide to the Northwestern University Settlement Association Records Case Files 1908/1975
Filing: Northwestern University Settlement Association Records Case Files

BMRC.NU.SETTLEMENT_CLUBS_CLASSES.xml
 Title: Guide to the Northwestern University Settlement Association Clubs and Classes Attendance and Registration Cards 1886/1941
Filing: Northwestern University Settlement Association Clubs and Classes Attendance and Registration Cards

BMRC.NU.SETTLEMENT_FINANCIAL.xml
 Title: Guide to the Northwestern University Settlement Association Records Financial Records 1918/1971
Filing: Northwestern University Settlement Association Financial Records

BMRC.NU.PAPENGELIS.xml
 Title: Guide to the Betty Ann Papangelis (1925- ) Papers 1965/1970
Filing: Papangelis, Betty Ann (1925- ) Papers

BMRC.NU.FISHER_OHARE.xml
 Title: Guide to the Leigh Fisher Papers related to Chicago O’Hare International Airport 1960/1962
Filing: Fisher, Leigh Papers related to Chicago O’Hare International Airport

BMRC.NU.EXUM.xml
 Title: Guide to the William H. Exum (1942-1986) Papers 1965/1985
Filing: Exum, William H. (1942-1986) Papers

BMRC.NU.STUDENTPROTESTS.xml
 Title: Guide to the Student Protests and Strikes at Northwestern University 1965/1979
Filing: Student Protests and Strikes at Northwestern University

BMRC.NU.TRANSP-CTR_REPORTS.xml
 Title: Guide to the Transportation Center Research and Consulting Reports 1966/1982
Filing: Transportation Center

BMRC.NU.SOWERBY.xml
 Title: Guide to the Leo Sowerby music manuscripts 1911/1995
Filing: Sowerby, Leo music manuscripts

BMRC.NU.BRUTUS.xml
 Title: Guide to the Dennis Brutus (1924-2009) Papers 1960/1984
Filing: Brutus, Dennis (1924-2009) Papers

BMRC.NU.COLTER.xml
 Title: Guide to the Cyrus Colter (1910-2002) Papers 1935/1995
Filing: Colter, Cyrus (1910-2002) Papers

BMRC.NU.ANTI-VIETNAM-WAR-STRIKE.xml
 Title: Guide to the Anti-Vietnam-War Strike Materials 1970
Filing: Anti-Vietnam-War Strike Materials

BMRC.NU.HERSKOVITS-BIOG.xml
 Title: Guide to the Melville J. Herskovits (1895-1963) Biographical Materials 1920/1996
Filing: Herskovits, Melville J. (1895-1963) Biographical Materials,

BMRC.NU.HERSKOVITS.xml
 Title: Guide to the Melville J. Herskovits (1895-1963) Papers 1906/1963
Filing: Herskovits, Melville J. (1895-1963) Papers

BMRC.NU.SETTLEMENT_FOOD.xml
 Title: Guide to the Northwestern University Settlement Association Food Client Records 1985/1986
Filing: Northwestern University Settlement Association Food Client Records

BMRC.NU.SETTLEMENT_PHOTO.xml
 Title: Guide to the Northwestern University Settlement Association Records Photographs 1890/1991
Filing: Northwestern University Settlement Association Photographs

BMRC.NU.SETTLEMENT_SCRPBK.xml
 Title: Guide to the Northwestern University Settlement Association Records Scrapbooks 1917/1984
Filing: Northwestern University Settlement Association Records Scrapbooks

BMRC.NU.FORREST.xml
 Title: Guide to the Leon Forrest (1937-1997) Papers 1952/1998
Filing: Forrest, Leon (1937-1997) Papers, 1952-1998

BMRC.NU.SETTLEMENT_ADMIN.xml
 Title: Guide to the Northwestern University Settlement Association General Administrative Records 1892/1995
Filing: Northwestern University Settlement Association Records General Administrative Records inu-ead-nua-archon-1236

BMRC.NU.YOUNG_QUENTIN.xml
 Title: Guide to the Quentin Young Papers 1937/2002
Filing: Young, Quentin Papers

BMRC.NU.CPC.xml
 Title: Guide to the Records of the Citizens' Police Committee (Chicago) 1928/1933
Filing: Citizens' Police Committee (Chicago), Records of the inu-ead-nua-archon-1013

BMRC.NU.FLOWERS.xml
 Title: Guide to the Katherine Flowers (1896-1982) Papers 1934/1981
Filing: Flowers, Katherine (1896-1982) Papers

BMRC.NU.FLAGG.xml
 Title: Guide to the Ann Kathryn Flagg (1924-1970) Papers 1941/1988
Filing: Flagg, Ann Kathryn (1924-1970) Papers

BMRC.NU.SETTLEMENT_JRBOARD.xml
 Title: Guide to the Records of the Northwestern University Settlement Association Records North Shore Junior Board 1937/1992
Filing: Northwestern University Settlement Association Records North Shore Junior Board, Records of the

BMRC.NU.AFR-STUDIES_TAPES.xml
 Title: Guide to the Program of African Studies Lecture Series Audiotapes 1965/1978
Filing: Program of African Studies Lecture Series Audiotap

BMRC.NU.SETTLEMENT_WOMANS-BD.xml
 Title: Guide to the Records of The Northwestern University Settlement Association Evanston Woman's Board 1911/1990
Filing: Northwestern University Settlement Association Evanston Woman's Board, Records of

BMRC.NU.BARNETT_C_RSRCH.xml
 Title: Guide to the Claude Barnett Research Collection 1950/1970
Filing: Barnett, Claude Research Collection, circa 1950-1970 BMRC.NU.BARNETT_C_RSRCHinu-ead-afri-0009inu-ead-afri-520

BMRC.NIU.SHAWL.xml
 Title: Guide to the Nisi Shawl Papers 1953/2014
Filing: Shawl, Nisi Papers

BMRC.NIU.BLK_STUDIES_CTR.xml
 Title: Guide to the Black Studies Center 1971/1987
Filing: Black Studies Center

BMRC.NIU.MOTLEY_W.xml
 Title: Guide to the Willard Motley Papers
Filing: Willard Motley Papers

BMRC.NIU.ROCKFORD_URBAN_MINISTRIES.xml
 Title: Guide to the Rockford Urban Ministries Records 1962/2017
Filing: Rockford Urban Ministries Records

BMRC.NIU.OKORAFOR.xml
 Title: Guide to the Nnedi Okorafor Papers 2005/2009
Filing: Okorafor, Nnedi Papers

BMRC.NIU.PEOPLEWHOCARE.xml
 Title: Guide to the People Who Care Records (Rockford) 1969/2007
Filing: People Who Care Records (Rockford)

BMRC.NIU.LIPSCOMB-DNC1968.xml
 Title: Guide to the Lipscomb Collection : 1968 Democratic National Convention (Chicago) 1968
Filing: Democratic National Convention, 1968, Lipscomb Collection (Chicago)

Please let me know what you think of this. To implement sorting by filing titles, I am probably going to add filing titles to everything in the regularization step- if there is an explicit one in the finding aid I'll use that, otherwise I'll just copy the non-filing title. 

If this works for you I can go ahead and implement this- but please note the low number of filing titles that are present (a bit less than 5% of the finding aids have them.)

**Comment by MomoMoses** [comment]
Let me check on this one. I don't want to see a bunch of "guide to the" or
"the", etc , but I'm not sure how the will come out in the end.
I guess if the 5% looks better that's fine but for most it would amount to
no change. Is that right?

**Comment by johnjung** [comment]
That's right- no change for the other 95%.

**Comment by MomoMoses** [comment]
Did we decide to add filing titles in the regularization step? That is, for the 95% where they are not supplied. That means we'd have to infer the proper title or something, yes?

**Comment by johnjung** [comment]
I haven't implemented anything yet because as of April 22 you were checking on this. Above you said you "don't want to see a bunch of 'guide to the' or 'the', etc." - my understanding is that filing titles would be used for sorting only, and if "Guide to the..." appears in a finding aid title that would still appear in the interface.

**Comment by MomoMoses** [comment]
After discussion today, we determined that trying to parse names in a programmatic way from the data, so as to reverse first name and last name (as distinct from family name, etc.) is not do-able. Any solution we could find for the cases where the institution did not supply a "filing" attribute for the title (95% of the existing finding aids) would add a lot of manual editing. Not feasible at this time. NOTE: the BMRC might suggest this as a best practice for our members, but as it now stands, this is not able to be resolved in a satisfactory manner, given staffing.

**Comment by MomoMoses** [comment]
We may find that the "Guide to the..." type issue is resolved when we resolve Issue #134 .
