### ISSUE TITLE
Blank data for field "Extent" in SERP 

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#141]
On a SERP page, the Extent field is blank if there is not an explicit `<extent>` used in the data. (These will still show data in the "Size" field in the Descriptive Summary in the finding aid if there is data in a `<physdesc>` element.)

**Comment by johnjung** [comment]
It seems to me that there are two potential ways to solve this problem:

1. Continue using the `<extent>` element, but if the element isn't present don't display an "Extent" label on the search snippet.
2. Switch from `<extent>` to <`physdesc>`. Consider changing the search snippet label to something more appropriate. 

Do you have a preference for which makes more sense?

**Comment by MomoMoses** [comment]
Extent is a really important first glance type of filter, so #1 is not a go. If you mean that there simply wouldn't be any information about the extent/size of the collection at all in the SERP. It makes a big difference whether the collection is 0.5 linear feet or 236 boxes in terms of plans and research interest.

The problem is with EAD of course -- there may be "extent" data without an `<extent>` element! arrrgh! As you discovered in your data review -- the data may simply be enclosed by a `<physdesc>` element.

The snippet label "Extent" is fine for either `<extent>` OR `<physdesc>` because both implementations are indicating the size of the collection.

If we were to switch to #2 approach, would we still capture the `<extent>` elements that are nested within the `<physdesc>` element? And would it capture more than one nested `<extent>`?

**Comment by johnjung** [comment]
If we start using `<physdesc>` we can capture all descendant elements- whether they are one or more `<extent>` elements or something else.

**Comment by MomoMoses** [comment]
Excellent

**Comment by MomoMoses** [comment]
So far I've found a handful of CHM finding aids with this issue: just a physdesc element and a text node, no descendant elements. I'm assuming that would render OK on the SERP too.

**Comment by johnjung** [comment]
This is fixed in https://github.com/uchicago-library/bmrc/commit/3bbad0789655cfb88cc6280a8021564618cb6010 and live on the server. 

Here is some reporting about this (of 1363 finding aids total):

1183 have both a `<physdesc>` element and an `<extent>`. (See BMRC.HARSH.AMOS.xml, and see BMRC.CHM.CHI-COMMONS-ASSOC_VISUAL.xml for an example with more than one `<extent>`). 
173 have a `<physdesc>`, but no `<extent>`. (See BMRC.HARSH.MINOR_FRANCES.xml)
0 have no `<physdesc>`, but an `<extent>` does exist. (No examples.)
7 have no `<physdesc>` and no `<extent>`. (See BMRC.NU.FERRIS.xml)

Because there are 7 finding aids where neither a `<physdesc>` or an `<extent>` is available, I added some code to suppress the extent label from the SERP snippet in those cases. 

In the current set of finding aids `<physdesc>` is always located at ead:ead/ead:archdesc[1]/ead:did[1]/ead:physdesc. `<extent`> elements are always direct children of `<physdesc>`, if they exist.
