### ISSUE TITLE
container inventory: labels displaying on top of other text

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#156]
The attempted columnar display of the container list is not working in some cases.
BMRC.DEPAUL.SMITH-CHARLES.xml
Information on the left does not wrap and is overwriting the label "Box" with the number in the next "column."

**Comment by johnjung** [comment]
Because there are so many inventory container variations, all with different content widths, a simple way to change this is to make the text in the first column wrap when it's too long for its container. Here's an example that sets the overflow-wrap CSS property to "anywhere". 

Current display:
<img width="1016" alt="without" src="https://user-images.githubusercontent.com/10198227/164751342-ffb9a218-a458-45aa-8c05-3156c6cdb30c.png">

With overflow-wrap: anywhere:
<img width="1016" alt="with" src="https://user-images.githubusercontent.com/10198227/164751386-d61ac500-92c0-48cc-bbe7-6a70d5062078.png">

Please let me know if this works.

**Comment by MomoMoses** [comment]
This looks great!

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/993875ba9b04c20b1039c340ca04f4e11f7954cc and live on the server. Please take a look and let me know if this is ok.

**Comment by MomoMoses** [comment]
Oops, late confirmation. Yes, fixed.
