### ISSUE TITLE
Accessibility: search button (magnifier icon) for WEBSITE

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#159]
The magnifier icon next to the search box with microcontent inside "search website" is flagged for not having alt text.
Not sure if this can be dismissed or not since most people would press "return" after encountering the searchbox.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/uchicago-library/bmrc/commit/97ef9a5b186b9a760654e11a3dab57c704d43102, and live on bmrc-test.lib and bmrc.lib. I checked Siteimprove to be sure this resolves the issue from their perspective- it does, so I'm going to close this issue out- but please feel free to re-open it if necessary.
