### ISSUE TITLE
North Park U name showing up in abbreviated form

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#166]
To demonstrate the issue, search for "cedarleaf" in the search box. There is 1 result at North Park University. On the SERP, the Archives field shows "Northpark" (clickable) rather than the full name of the repository. 

There doesn't seem to be a way to access this from Wagtail admin side.

**Comment by johnjung** [comment]
It looks like you already updated the Archive object in the Wagtail admin, so in order to get this change to show up in the interface I'll need to reload the finding aids. Are the finding aids in ead/bmrc/clone/portal in a state where they can be reloaded?

**Comment by MomoMoses** [comment]
Not yet ready. Give me a day?

**Comment by johnjung** [comment]
It's no problem- please let me know when you're ready.

**Comment by MomoMoses** [comment]
Files have been re-loaded this week, but the SERP still shows: " Archives: [Northpark]" rather than a more complete name as entered in the Archives information. Is it because it is forming a clickable link???
???

**Comment by johnjung** [comment]
Oh- this happened because I loaded the finding aids from bmrc-test.lib, to avoid taking the finding aids offline on bmrc.lib for a few minutes. The best way for me to correct this would be to load the finding aids from the production server. If I do that, they will be unavailable for about 5 minutes. Would today or Friday morning around 8AM be an ok time for me to do that?

**Comment by MomoMoses** [comment]
I'd rather have things always go from production server I guess if anomalies will be introduced otherwise. I'm sure it's fine to have a 5-minute gap! Let's wait until Friday morning, actually--I'm working on some other data issues, and may as well catch 'em all in one go!
