### ISSUE TITLE
Non-clickable indexed terms

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#29]
Subject headings lists include topics, names of people, and names of organizations. It is desirable for ALL of these to be clickable; however, only the topics are.

**Comment by johnjung** [comment]
I'm going to address this next- I'll hook up places too. 

As I reviewed the code that builds our browses, I see that we're catching namegrp elements for the person browse. However, namegrp is allowed to contain elements that aren't related to people. (e.g. corpname, genreform, geogname.)

I checked our finding aids, and I see that we're not currently using namegrp anywhere.

If you have a sample of the way this element would appear in the wild that I can use for testing, please send it along. Otherwise, is it ok for me to remove it from the browse-building code, and skip implementing it in the finding aid viewer?

**Comment by MomoMoses** [comment]
I looked in the NAFAN data and <namegrp> does not appear at all.
It seems to be part of a fabric of support for indexing and local anchor-style linking within the document. I would say it's fine to ditch the whole magillah! That is, <indexentry>, <ptr>, and <namegrp>, <ref>, and <ptrgrp>.

**Comment by johnjung** [comment]
I'm going to close this issue out- please re-open it if necessary.
