### ISSUE TITLE
Finding aid viewer: sticky sidebar

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#31]
Guide to the ACLU Illinois Division, UChicago, is the example. [ACLU Illinois](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.UOC.ACLU_IL.xml#idp61055104)
Scrolling down or clicking a link in the nav sidebar that goes below the sidebar length takes me to a page location that does not offer a way to get back except for scrolling.

Possible common solutions: 1. the LH sidebar TOC follows you as you scroll down 2. sections have a "back to the top" anchor link at the side (usually RH)

**Comment by johnjung** [comment]
If you'd like to review other interfaces to see how they solve this problem, please do, and let me know what you'd like to try. I'll tag this one "design" no matter what, but if you'd like to try something in the meantime just let me know.

**Comment by johnjung** [comment]
I'm going to leave this for design, since the UChicago interface uses a fixed sidebar for the table of contents and smooth scrolling, which is now available as "scroll-behavior" in CSS. If there are markup changes I can make, just let me know.

**Comment by MomoMoses** [comment]
another site solution: also a fixed sidebar - [https://archiveswest.orbiscascade.org/ark:/80444/xv62237/op=fstyle.aspx?t=t&q=Arts%2c+Humanities%2c+and+Social+Sciences&f_subjects=Personal+Papers%2fCorporate+Records+(University+of+Washington)](url)

**Comment by johnjung** [comment]
Laurie, is it possible to collect a few more solutions from well-designed finding aid viewers? 

There are some usability issues I'm trying to avoid here. For example:

- Right now the entire portal, including the finding aid viewer, uses a fixed nav at the top of each page. If we include an additional fixed side nav on the finding aid viewer, we need to make sure that the two navs are not confusing to users, and we need to make sure that interface elements fit together in the viewport in ways that make sense. (Alternatively, we might want to omit the top nav from the finding aid viewer, etc.)
- A fixed sidebar navigation requires scrollbars, since the content can be taller than the viewport. Inner scrollbars create [some](https://www.nngroup.com/articles/scrolling-and-scrollbars/) [usability](https://baymard.com/blog/inline-scroll-areas) [issues](https://uxmag.com/articles/the-extinction-of-the-scrollbar) that we should be aware of.
- We may want to omit the sidebar navigation on mobile devices, or design it in a way that makes sense for mobile, since it's easy for it to take up a lot of space in the viewport if we're not careful. 
- We should be careful with accessibility issues here too, since usability issues might magnify problems with keyboard navigation, etc. 

Seeing a few more examples of how other sites have solved this problem will help us avoid re-inventing the wheel here.

**Comment by kzadrozny** [comment]
My recommendation would be **not** to use a sticky sidebar and instead use something like an "off canvas" [collapsible menu](https://www.w3schools.com/howto/howto_js_off-canvas.asp) for the sidebar in mobile. We use this method on the Library site with great success and ADA compliance.
Using this along with a "scroll to top" button that shows up as you scroll down the page will create a better user experience. We use the "scroll to top" button on our subject guides and it is something I've been considering adding to the Library site.

**Comment by MomoMoses** [comment]
Can we use the sticky sidebar, as indicated by Kathy's code above, and use the "off canvas" for the mobile display?
In either case, it couldn't hurt to have a "scroll to top" button.

**Comment by MomoMoses** [comment]
Ok, let's go with Kathy's solution for this launch. Thanks KZ!

**Comment by johnjung** [comment]
Thanks very much, Kathy. Could you copy and paste a URL where I can see how this is set up on the library site?

**Comment by kzadrozny** [comment]
Any page with a sidebar uses this; the Law homepage is a good example: https://www.lib.uchicago.edu/law/
You can see the template code in our Library base template: https://github.com/uchicago-library/library_website/blob/a3e39ff95613c36d40cdfdfd25291ec1e57ff556/base/templates/base/public_base.html#L138
Most of the heavy lifting is in the template structure; the JS is minimal: https://github.com/uchicago-library/library_website/blob/master/base/static/base/js/offcanvas.js

**Comment by MomoMoses** [comment]
As for better examples of an easily accessed/accessible sidebar, honestly, they're hard to find. Let's go one better!

**Comment by MomoMoses** [comment]
Also noticed that for a full SERP, the page seems very long to scroll. Similar solution = back to top link with mobile-friendly sidebar.

**Comment by johnjung** [comment]
Going to implement "back to top links" based on our Zoom conversation today.

**Comment by MomoMoses** [comment]
Understood that this enhanced nav comes after making the pages and ingesting the data! :)

**Comment by johnjung** [comment]
As per our Zoom conversation, this is optional for the December 10 launch.

**Comment by MomoMoses** [comment]
> Going to implement "back to top links" based on our Zoom conversation today.

What's the latest thought about having these links implemented? Is February possible?

**Comment by johnjung** [comment]
Implement this as "back to top" links.

**Comment by MomoMoses** [comment]
Can Kathy's solution be implemented using the library base code she referenced? please indicate your understanding of the extent and scope of this task as outlined by Kathy above.
"Go with the mobile-friendly sidebar + "scroll to top" for this launch"

**Comment by MomoMoses** [comment]
Has this been dropped from the launch to-do list?
Let's discuss where this should go in the post-launch to-do list if so (as I am guessing it will need to be done later).
