### ISSUE TITLE
Inventory / container list display

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#35]
The example is from [Archives West](http://archiveswest.orbiscascade.org/ark:/80444/xv24154/op=fstyle.aspx?t=t&q=African+Americans#dscID)
After a descriptive sentence or three for Subgroup 1, there is a table format.
Above the table columns are the labels "Container(s)" | "Description | Dates
Below those labels with a horizontal line is "Series 1: Label" (bolded) with the Dates for the series and a brief description of the Series beneath (not bolded). Doesn't necessarily need to be indented.
Below that is another horizontal line, with different color heading in the leftmost column "Box/Folder". The number of folders is on a line below the title of the materials grouping. I don't think that's entirely necessary.

#Design

**Comment by johnjung** [comment]
Tagging this one for design. If there are coding changes I can make, please let me know.

**Comment by johnjung** [comment]
Please confirm: is [https://uchicago.app.box.com/file/807084219878?s=86ze2stummldz0bma0ek278dl9k7nphr](https://uchicago.app.box.com/file/807084219878?s=86ze2stummldz0bma0ek278dl9k7nphr) the best mockup this issue?

If so, comparing the mockup to the example from Archives West, could you list the specific qualities are better in the Archives West inventory? (I might want to mock this up again with a few different finding aids, since there is a lot of variation in the way finding aid authors use `<did>` elements.)

**Comment by MomoMoses** [comment]
Caveat to using the finding aid mock table display as is: we may need a "column" for dates. Not all finding aids incorporate the dates into the title of the container/series.

**Comment by MomoMoses** [comment]
that Box link is our Finding Aid mockup final from Kathy.

**Comment by MomoMoses** [comment]
**What I like about the Archives West example:**
It is visually clear.
Columns: "Container(s)" | "Description"| "Dates" at the top in visually distinct columnar layout.

Series number and title are distinct and bolded to highlight compared to the descriptive text below. Description for Series is directly below the Series number and title line. Dates are also bolded as part of the Series number and title line. This indicates to me that the dates apply to that Series as a whole vs. a container.

"Box/folder" heading row helps to show that the content is now a container list. Though enumeration systems may vary, this layout will help the user understand the separate groupings. The "Description" and "Dates" columns are understood to carry through to the container list. That seems clear to me.

I DON'T like having the number of folders on a line below the title. Not sure it's even necessary to indicate it--one can infer that information from the numbering system in this case, at least.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/8b3787396077f12abd93d18cf776ea47111856e1, and live on the server. Please take a look and let me know what you think. I tried to implement this so that it goes along with the grain of the mockup as much as I could, while taking the concerns you listed into consideration. 

Please let me know if there are other things you'd like to try here. (And please keep in mind that because of the amount of variation between finding aids, that it can be tricky two write a transform that works everywhere.)

**Comment by MomoMoses** [comment]
This looks good, very much like the mockup. I like this better, with the container label "Box" or "Folder" right next to the number, in order, vs. having a heading to a faux "column." 

Only thing that shows up a little differently than the mock or Archives West is having [the date(s) on the next line below the description line.](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.BROWNING.xml#dsc) Kathy had the dates in line with the description on the mock (not sure this is do-able unless the data has it that way). 

This isn't bad, just adds more lines! And some duplicative text.) All the more imperative to be able to get "back to top" easily.

**Comment by johnjung** [comment]
I'd like to leave this as-is, if we can. Putting dates in their own column wouldn't work for at least one finding aid, where the dates are tagged, but they're basically part of the `<unittitle>` and they're meant to be read along with the `<unittitle>` as a phrase. 

Is it ok to close this one out? (I'll add the "back to top" separately.)

**Comment by MomoMoses** [comment]
Yep ok to close.
