### ISSUE TITLE
Curated topics on mobile

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#41]
Featured topic display is stacked on mobile: makes the image and heading seem to appear twice for no apparent reason

**Comment by johnjung** [comment]
Consider https://github.com/johnjung/bmrcportal/issues/12 along with this issue.

**Comment by kzadrozny** [comment]
I'm recommending the image in "Feature topic" is hidden in mobile, rather than what I believe Laurie is requesting which is to hide the second thumbnail, which is in the body of the page. The size of the thumbnail shouldn't be in conflict with whether or not it is visible in mobile as in all non-mobile sizes it will be shown in that size.

**Comment by MomoMoses** [comment]
OK, so when the user clicks to the content description for the Featured Topic on mobile, they won't see the image at all, is this correct? I don't think that's a problem, as they will have seen it before they clicked on the Home Page, presumably. 

Could we/should we add a link to "View image"? if they want to see just the included image/eye candy?

**Comment by kzadrozny** [comment]
My mobile view technique is to only hide things when it is helpful or useful to the user. Images are one of the best things to hide in order to allow users to get straight to the content. If you hide an image, especially if it is decorative, there is no need to let the mobile user know what is being hidden or to ask them to take an action for something that is not imperative to them completing a task.

**Comment by johnjung** [comment]
I agree with Kathy's comment above. Laurie, please let me know if that solution is acceptable. If so, I'll hide the sidebar "featured topic" image on mobile.

**Comment by MomoMoses** [comment]
YES. Let's do this. Thanks for that insight, Kathy about not offering something they don't need!

**Comment by johnjung** [comment]
Excellent- thanks very much, both of you. This is now implemented in https://github.com/johnjung/bmrcportal/commit/ba6af14411d0bb7f9c240c304d73931554aae366 and live on the site. I'm closing this issue out, please feel free to re-open if necessary.
