### ISSUE TITLE
Mobile display: Viewing all relevant topics

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#42]
Very narrow white band appears with no content preview blocks. Maybe modal window could be wider? The "X" to close that modal is below the text. Should show in RH corner, not part of content

**Comment by johnjung** [comment]
I'm going to tag this as "design", because this seems to be design related. Please clarify the issue when you have a chance.

**Comment by johnjung** [comment]
This is now implemented in https://github.com/johnjung/bmrcportal/commit/6151260f84915acc4901e3006bb9dbbdb13e6f49. Please take a look and let me know if this works.

**Comment by MomoMoses** [comment]
11/3: I can't test this right now as my mobile phone is non-operational, and my desktop is too fast to show the narrow white band. Will need to borrow a phone this evening.

**Comment by MomoMoses** [comment]
This appears quickly as a large modal which is good (a bit too large?) Can't see the "x" to close it though. Could be a width issue.

**Comment by MomoMoses** [comment]
The "X" is way too far to the right, even on the desktop. I don't know how these work, but perhaps the container for the modal content is too large? Or the "X" is simply placed with too much distance between itself and the window.... ?

**Comment by MomoMoses** [comment]
I've seen similar modals with a circle with an 'x' in the middle that looks kind of attached to the upper RH corner of the display portion of the modal window. At least that way it might adjust according to how the modal window displays, vs. straying way off to the right.

**Comment by johnjung** [comment]
In this case, we're using the default position for the "X" provided by Bulma. I think it's safe to say that they've done user testing on that part of the design, so my preference here is to look out for problems on our site in testing, but leave the "X" where it is for the time being. 

You can see an example on [the Bulma website](https://bulma.io/documentation/components/modal/)- click the button that says "Launch example modal". 

Does this sound like an ok approach to you?

**Comment by MomoMoses** [comment]
I did look at that site -- however the "X" to close the window is still way far to the right, and not obvious at all. People do know to look for it, but it shouldn't be that far from the corner.

Mobile view: just emailed you a screenshot -- the X is not visible at all.

**Comment by johnjung** [comment]
Ahh- I see that when we moved the modal window to the top of the screen, we covered the "X" at narrow screen widths. I moved the modal back down to the middle of the screen vertically. This more closely matches the Bulma defaults, which have been usability tested by lots of the sites that use Bulma. This is fixed in https://github.com/johnjung/bmrcportal/commit/6a5ef62b5fc1d4e92be37b5572b0553b9c264ca9 and live on bmrcportal-test. 

Please take a look and let me know what you think. Because we're matching Bulma's defaults more closely now, if you're still uncomfortable with the positioning of any elements, I'd like to consider that a research issue that we could test later.

**Comment by MomoMoses** [comment]
Ah good. Glad you found the issue! I'll check it out.
