### ISSUE TITLE
pagination: should we add a "Previous page" button?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#43]
The results line looks good, one can click on pages by number, current page is greyed out. "Next page" button is available. But having clicked on it, you can't choose to go back a page using a button.
The browser back button or clicking on the lower number in the page buttons will do it though.
So--is it needed?

**Comment by MomoMoses** [comment]
Agreed. Not trying to match another site, though I have often seen "Previous" buttons, often highlighted in a different color than the "Next" button.

**Comment by johnjung** [comment]
Do we have a mockup that shows pagination?

**Comment by kzadrozny** [comment]
We already have pagination active in the results template on test server. It is using Bulma's pagination: https://bmrcportal-test.lib.uchicago.edu/search/?q=hampton
There are mocks that show the pagination in our Mocks directory in Box. Here is one example: https://uchicago.box.com/s/1laay3kuo5q9vdo6olbyid0991hyahea

**Comment by johnjung** [comment]
Laurie and I had a conversation about this a few months ago. At that time, we decided to omit the previous page button, since users can just use the back button or the page links to visit a previous page. Because stakeholders have already signed off on mockups that omit a previous page button, I'm going to tag this as "research". If user testing shows that the previous page button would be helpful, we can add it back- but at this point I prefer matching mockups as close as we can.
