### ISSUE TITLE
finding aid viewer sidebar too wide

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#51]
[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.ABBOTT_SENGSTACKE.xml](url)
LH sidebar is not wrapping long text lines, such that the Super Series titles expand the shaded area to about 2/3 of the entire width of the page. 

Data error: repository info is appearing on the TOC sidebar due to long content.

**Comment by johnjung** [comment]
Note that adding archive contact information to the sidebar for the finding aid viewer increased the width too.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/57834adcb35e9d61c943a217b24ef0063b802c50, and live on the site. Please note that I kept the member institution logos smaller than 150px-300px. I think that recommendation makes sense for thumbnails, but less so for logos- especially in cases where it would mean that the member institution logo becomes larger than the BMRC logo in the upper left corner of the site. 

I think that it's relatively common for logos in the content area of the page to be a bit smaller than thumbnails when they appear in the content area of a site. If these  still seem a bit small please let me know and I'll increase the size a bit- however I don't want to increase the size too much, since the current size is close to what I see on the mockups (which have already been signed off on.)

**Comment by MomoMoses** [comment]
Agree with the decision to make smaller thumbnails for the logos.

Please note that our student worker can edit and regularize the logos if that needs to be done.

**Comment by johnjung** [comment]
Ok that's great. I'm going to close this issue out- if you'd like to open a new issue for the logos themselves please do. (And please re-open this issue if you need to.)
