### ISSUE TITLE
<extref> website links not clickable

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#52]
[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.HARSH.ABBOTT_SENGSTACKE.xml#idp120040192](url)

The link to the Mapping the Stacks project is encoded as `<extref>` with the appropriate attributes (I think!) but it does not create a real link to click in the finding aid displayed document.

[https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.UOC.AVC_CHI.xml#idp23224448](url)
`<archref>` `<extref>` does not create a clickable link.

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/d124b5ec7948e184fab650e2fb0d267fa8aa80f0, and this is live on the site. 

Please note that the href in BMRC.HARSH.ABBOTT_SENGSTACKE.xml is malformed- it should contain a leading "http://". 

It used to be that you could specify a "protocol-relative URL", where the URL began with a "//". That would have been useful in this situation, since websites like Mapping the Stacks should hopefully migrate from http to https. However, it's better to specify the protocol explicitly- [there is some discussion and some links about this here](https://stackoverflow.com/questions/9161769/url-without-httphttps). 

I'm going to tag this one "data" so you can keep track of it- if you'd like me to close it out please just let me know.

**Comment by MomoMoses** [comment]
Let's track it. Might need to manually edit these malformed links. Doesn't seem that it would be that many.

**Comment by MomoMoses** [comment]
bug in Oxygen, or schema, or missing some step
try using Notepad++

**Comment by MomoMoses** [comment]
working on this: the simpler the better seems to be the way to go!
just `<extref>` with attribute href= and the URL to point to. Works on UChicago finding aids....
retroactive project to fix broken link references in the data when time.
