### ISSUE TITLE
Find a better label for TOC (?) or remove heading ?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#69]
I'm not sure about the heading "Contents" -- some people may be confused, as container lists and inventories may be better understood as describing the contents of the collection, and that's not what it refers to.

Do we need a header here at all? That is the question. Or is it not confusing at all.

**Comment by johnjung** [comment]
I don't find this label confusing- however, if you'd like to see if there are ways to improve the label, my recommendation is to look at the list of other good finding aid viewers to see if they use a different label, or omit the label, for this part of the interface. 

I'm going to tag this issue as "spec" so you can keep track of it- but if you'd like to close it out please feel free. Otherwise, if you decide on a new label for that section just let me know.

**Comment by MomoMoses** [comment]
I snooped around, but mostly couldn't find anyone labelling it! I'll get to this later and give you the word on it. :)

**Comment by MomoMoses** [comment]
please label "research" and close.
