### ISSUE TITLE
Make logos uniform in size and resolution

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#77]
Set a guideline for size of sidebar institutional logos. Might be a range with optimum size indicated--100px X 100px? Do we want square or rectangular?

Avoid low resolution images -- what is a good cutoff? 150dpi? with preferred 300?

**Comment by johnjung** [comment]
We should try to get logos that are as easy as possible to resize- ideally, the graphic designer for each institution supplied them with high-quality logo files that can be used in lots of different situations. Here is my rough order of precedence for files like this:

1. Ideally, the logo is in a non-proprietary vector format like SVG.
2. Otherwise, the logo is in a proprietary vector format like Adobe Illustrator.
3. Otherwise the logo is in a faster format like PNG, but there is an anti-aliased transparency channel that will let us put the logo on whatever background we'd like. The resolution should be as high as possible. (2000x2000 is a common size to see for files like this.)
4. Otherwise the logo is in a rasterized format like JPG, without a transparency channel. The resolution is as high as possible, and there is as little compression as possible on the image. 
5. Otherwise we'll take what we can get. The image file might use high compression, or a limited number of indexed colors like GIF or indexed PNG, or is low resolution. (There will be a perceivable loss of quality if we start from an image file like this.)

Vector formats are easy to resize however we'd like. Ideally the file will also use a color space so we'll get accurate color. Designers sometimes include additional information about how to use their logo, etc. For an example, [here's the site](https://creative.uchicago.edu/resources/) UChicago put together for resources like logo files. 

I hope this helps!

**Comment by MomoMoses** [comment]
This is great. I will put this on Warren's investigative list and see what we find out!

**Comment by MomoMoses** [comment]
we'll standardize the logos and the guidelines to members for logos in 2022.
