### ISSUE TITLE
"Results 1 to 1 of 1" ... weird label! For only 1 result for a search term.

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#78]
To illustrate how I got those "results" -- I clicked on the random feature that displayed "Herbert Paschen" -- all I got was the Defender Individuals collection, and the "Results 1 to 1 of 1" label at the top.

"Results 1 to 1" could be the most confusing part of this -- can we suppress something when there's only 1 result? It could say "Results 1 of 1" ... ?

Not a big deal -- probably doesn't happen all that often.
#Phase Two (if you like)

**Comment by johnjung** [comment]
On the catalog (and several other library search interfaces) we solve this problem by automatically redirecting to the view for the result of a one-hit search result page. So, in this case, users would get redirected directly to the finding aid featuring Herbert Paschen. 

I have that coded up on my local machine- do you want to see what it looks like on bmrcportal-test?

**Comment by MomoMoses** [comment]
well that's an interesting thought... how do you indicate that this is why the behavior is different for this result vs. the behavior for other searches? i.e. that there's only 1 result, so here it is...

**Comment by johnjung** [comment]
We don't indicate the difference- but (maybe) since users are focused on "getting to the search result", they may not notice. 

If you'd like to try, go to https://catalog.lib.uchicago.edu/. If you do a search for "color", click format "map" and format "video" in the sidebar. If you scroll down, there should be some facets in the sidebar with a single result and some with 2 or more. Clicking "Russian" under Language currently has 2 results- if you compare that to "Chinese" with one result you'll see the difference. 

My preference is to solve the problem in the same way that we solve it for other search interfaces, if we can- but definitely let me know if this works for you here.

**Comment by MomoMoses** [comment]
Yeah you've got a point there -- goal oriented users. What the Portal does NOT have is "related stuff" on the RH side...
My guess is that folks would just use the back button if they didn't like where they ended up. Or do a new search. Tag this user research?
with this solution in mind or A/B test it -- have you all tested this solution?

**Comment by johnjung** [comment]
I'm not sure if the web team has tested this specific aspect of the behavior of the catalog. I could check on that- but if this doesn't immediately seem like a good solution to you, my preference is to tag this as user research and wait to implement any changes until after our December launch. Does that sound ok here?

**Comment by MomoMoses** [comment]
Sounds good to me!
