### ISSUE TITLE
refresh the random feature more often

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#79]
To help the user understand the transient and random nature of the RH surprise facet feature, if the user stays on the landing page longer than 0.5 seconds (or some duration that works), the facet refreshes. It would still refresh upon re-loading the page as well.

**Comment by johnjung** [comment]
I would prefer to wait and see if this solves a demonstrated problem before we implement something like this. The random facet on the homepage already shows users an example of the type of content that is in the system. Refreshing that content block more frequently might demonstrate that in a slightly more thorough way, but it would come with some potential downsides:

- Users may see a random feature they want to visit, but they aren't able to click the link in time. These users may find this annoying.
- Site visitors who use alternative input devices may find that it is difficult to click links in time, which would create an accessibility issue.
- I'm not sure how this would render for screen readers- screen reader users may find randomly updating blocks of content annoying, especially if they're visiting the site to use the search.
- Users may find a randomly updating block of content annoying because it competes for their attention when they're looking at other parts of the homepage. 

On the technical side, implementing a feature like this would mean creating a web service that could get the random content to JavaScript running in the user's browser. It isn't very difficult to set this up, but at this point in the project I'd prefer to launch what we have and save something like this for a possible enhancement: especially if we can demonstrate a need for it, either because the BMRC wants to promote the breadth of what is in the portal more, or because we find users still don't understand what kind of materials are in the portal. 

What do you think, can we mark this as a possible enhancement and save it for later?

**Comment by MomoMoses** [comment]
Absolutely! Mark it for later. Really appreciate the thorough analysis!
