### ISSUE TITLE
Emph tags don't render

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#82]
This may just be a data issue with NU. The code appears, not the styling.
Example: [NU dept of African American studies](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.NU.AFRSTUDIES.xml#arrangement)

**Comment by johnjung** [comment]
This is a data issue. The first `<emph>` tag that I see is under [Acquisitions Information](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.NU.AFRSTUDIES.xml#acqinfo). In the EAD itself, the angle brackets for these elements are encoded as `&lt;` and `&gt;`- because of this, when the XSLT transforms the page it passes them through as text, and when the browser displays the page it displays angle brackets rather than interpreting them as tags. 

I'll tag this as a data issue.

**Comment by MomoMoses** [comment]
Thanks! I didn't have a chance to check that yet. 😜
