### ISSUE TITLE
missing content on finding aid

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#83]
This finding aid appears in search results, but displays blank.
[what's up with Vernon McKay?](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.NU.MCKAY.xml)

#data

**Comment by johnjung** [comment]
In this finding aid, the `<archdesc>` element's audience attribute is set to "internal"- so most of the finding aid isn't displayed. There are other audience attributes in this finding aid too- if you remove them that content will display when I re-import this finding aid. (I'd check with Northwestern first, since they specifically added them.)

**Comment by MomoMoses** [comment]
I'm sure they didn't intend for nothing at all to display! I can match it
against their own site.

**Comment by MomoMoses** [comment]
Emailed Northwestern. There are in fact other elements that are tagged "internal" that we would not need or be interested in, so they do use it purposefully. Not sure why `<archdesc>` would have that attribute. Awaiting response.
