### ISSUE TITLE
featured curated topic: template for content incomplete

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#84]
There is more content to be included on a curated topic feature page, per this example: 
[Black Studies](https://uchicago.box.com/s/3rhunvf7l1iml2olktpz5gp413i0uuyu)

1. Byline of author of feature copy
2. Caption for photo
3. Image URL
4. Citation for photograph source (one of the member repositories)

Content below the search links to follow. #content

**Comment by johnjung** [comment]
I can add a field for the author. The caption is already present. Regarding the image URL, do you really want to provide a link to a Box folder at Northwestern here? (I didn't realize this link was meant to be visible to the public.)

The citation is currently incorporated into the caption under the image. This made the most sense to me, because on this page the citation is secondary information. In my opinion, making that part of the page more visually prominent would be a mistake because it will visually interfere with the main content of the page.

This appears to be a continuation of https://github.com/johnjung/bmrcportal/issues/74- I'm going to close this issue out and make a note about adding the author there- please add additional notes to that issue.
