### ISSUE TITLE
Finding aid view: distinguish field labels from field content better in Overview section

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#86]
The italics for the field names in the collection view page may not immediately scan as different than the field values ... maybe a different font weight or a little space between label and value.

Let's try some other things towards the final polishing phase.
#design

**Comment by johnjung** [comment]
https://github.com/johnjung/bmrcportal/issues/24 addresses the underlying problem here, and includes some notes on things we've already tried. I'm going to consider this issue a duplicate and close it out. Issue 24 is already tagged "enhancement", but if you'd like to reopen that one so that it doesn't get lost please let me know.
