### ISSUE TITLE
clickable repository names in finding aid view?

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#87]
nice to have this clickable to show the view of all collections in the database at that repository -- exact same result as browsing by archives and clicking on one of the repository names.

[example at CSU not clickable](https://bmrcportal-test.lib.uchicago.edu/view/?id=BMRC.CSU.ICBCHE.xml)

**Comment by johnjung** [comment]
Please confirm the location of the repository name in the finding aid so I can evaluate this.

**Comment by MomoMoses** [comment]
Under descriptive summary, labelled "Repository."

**Comment by johnjung** [comment]
Thanks very much. This would be a bit tricky to implement: right now, finding aids are assigned a repository based on the middle chunk of their identifier- so for this example, in BMRC.CSU.ICBCHE, the "CSU" identifies a specific archive which gets named "Chicago State University" in the config file. 

However, the repository that appears in the descriptive summary comes from the archdesc/did/repository element. In this case the text of this element reads "Chicago State University, Archives and Special Collections."

This text is a bit different from what we specified in the config file- but because we don't have any procedure or code in place to insure that the repository element matches the repository name, there's nothing to keep the finding aid from specifying a different unit of Chicago State University apart from the archives, or even a different place entirely. 

To implement this, I should generate a report that compares the repository element to the one specified in the identifier, and confirm that for our finding aids, the two match. (We'd probably want to set that report up so we could run it on demand, to be sure new finding aids don't break the pattern.) Once we know they match, we could link to the specific archive regardless of what the text of the archive link actually says. 

I'm going to label this as "enhancement" but close the issue out for now, because it's going to be out of scope for phase two based on the amount of work we're already committed to. However, if you'd like to re-open the issue so that it doesn't fall off the radar, please do.

**Comment by MomoMoses** [comment]
Perfect idea to track it. Normally it's fine that it's not clickable as
you've described it, but the report you suggest could be a good way to make
sure errors don't creep in. There were several errors of this kind in the
"old" portal, which are seriously detrimental to the needs of constituents.
The filename and the repository didn't match.
