### ISSUE TITLE
round up of home page content only

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#92]
a[ roundup](https://uchicago.box.com/s/74j5308m1tfaj0ccose28mbqkpakoejq) of all the content - Box file for reference

Includes heading, narrative description, member highlight (note feature name change) +
narrative for curated topics list page

**Comment by MomoMoses** [comment]
Content is complete for home page. Issue can be closed when content has been revised.

**Comment by johnjung** [comment]
In https://github.com/johnjung/bmrcportal/commit/39782e40a8181d2e0405661b17528a623bf6860d, I added the following updates:

- Update the title on the homepage. 
- Update the introductory paragraph on the homepage. 
- Added links to a curated topic index page. 
- Created a curated topic index page. 
- Added links to the curated topic index page in the sidebar of the curated topics index and entry pages. 

I added text for the Northern Illinois University member spotlight to the config file, but I didn't activate that on the homepage yet since finding aids from Northern are still outstanding. Once those are added I'll update the homepage. I'm going to flag this issue as "data" and assign it to you in the meantime to keep track of it.

**Comment by MomoMoses** [comment]
the finding aids are there -- just need to ingest them.
not going to worry about the other two for now.

**Comment by MomoMoses** [comment]
Please note that the data for NIU is complete for now. It's in the folder "niu" on the server. Thanks!

**Comment by johnjung** [comment]
As per our Zoom conversation, change "MEMBER SPOTLIGHT" text on the homepage to "MEMBER HIGHLIGHT".

**Comment by johnjung** [comment]
This is now fixed in https://github.com/johnjung/bmrcportal/commit/dfa5c423a272d9867ef8ddb77060a72cba6464ba and live on the server. Please take a look. If this looks ok, please close out the issue.

**Comment by MomoMoses** [comment]
This looks great! I'm wondering now, looking at this, whether we want to put the link for their own website within the text of the highlight paragraph, so that the link to go to collections in the Portal stands out from that text. That's kind of how it was when we linked to the word "here" which is of course, deprecated. :)

**Comment by johnjung** [comment]
At this point, that would have to be a phase two change.

**Comment by MomoMoses** [comment]
You misunderstand! I'm simply saying, don't put the link to their site into a new paragraph. Wasn't it within the descriptive text before?? If I've forgotten, then OK, phase2. :)

**Comment by MomoMoses** [comment]
Home page will need a few text edits -- once we finalize the name of the Portal, plus some additional explanatory text for a better user experience. To be finalized after Board meeting on 1/19/2022.

**Comment by MomoMoses** [comment]
Narrative content including name, heading, etc. will be editable on Wagtail.
