### ISSUE TITLE
View all exhibits link ... to placeholder page

### ISSUE THREAD

**Issue by MomoMoses** [johnjung/bmrcportal#94]
To make sure that all links go somewhere when clicked, let's just give the "View all exhibits" link from the middle content block on the home page a placeholder page.
It can be very basic, with the headline ### BMRC Member Collections Exhibits
and a "Coming soon ..." text line below.
Kind of like [this page](https://bmrcportal-test.lib.uchicago.edu/about/) (which will soon have content ready -- I just have to find it, I know I already wrote it up!)

**Comment by johnjung** [comment]
This is implemented in https://github.com/johnjung/bmrcportal/commit/f2e7cbb597798b0452ebac58ececfe7411882573 and live on the server.

I did make one change: rather than giving the page the title above, I just gave the page the title "Exhibits"- I did this to keep the title and breadcrumb text more concise. Because "Black Metropolis Research Consortium" already appears in the breadcrumb trail, this avoids some duplication too. 

Please take a look and let me know if you'd prefer "Member Collection Exhibits", or something else here.
